name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: setup sbt
        uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: '2.0.18'
          ports: '8083:8083'
          config: ${{ github.workspace }}/.ci/mosquitto.conf
      - name: Run tests
        run: sbt -v "scalafmtCheckAll; +test;"
